In [14]:
import torch
import numpy as np

In [2]:
# How to denote string
# 0ne-hot / Embedding

In [3]:
# Type Check

a = torch.randn(2,3)

a, a.type(), type(a)

(tensor([[ 0.9814, -0.6438,  2.9055],
         [-1.0198,  0.4671, -0.4582]]),
 'torch.FloatTensor',
 torch.Tensor)

In [4]:
isinstance(a, torch.FloatTensor)

True

In [11]:
# Dim 0 , scaler

a = torch.tensor(1.0)

a, a.shape, len(a.shape), a.size()

(tensor(1.), torch.Size([]), 0, torch.Size([]))

In [12]:
# Dim 1 , vector

a = torch.tensor([1., 2.])

a, a.shape, len(a.shape), a.size()

(tensor([1., 2.]), torch.Size([2]), 1, torch.Size([2]))

In [18]:
b = torch.Tensor(3)

b, b.shape, len(b.shape), b.size()

(tensor([9.2755e-39, 1.0837e-38, 8.4490e-39]),
 torch.Size([3]),
 1,
 torch.Size([3]))

In [19]:
c = np.ones((2,3))
c = torch.from_numpy(c)

c, c.shape, len(c.shape), c.size()

(tensor([[1., 1., 1.],
         [1., 1., 1.]], dtype=torch.float64),
 torch.Size([2, 3]),
 2,
 torch.Size([2, 3]))

In [21]:
# Dim 2

a = torch.randn(2,3)

a, a.shape, a.size(0), a.size(1), a.shape[1]

(tensor([[-1.7118, -0.5592,  0.0322],
         [ 0.5100,  0.0161,  0.7659]]),
 torch.Size([2, 3]),
 2,
 3,
 3)

In [22]:
type(a.shape)

torch.Size

In [23]:
# Dim 3

a = torch.rand(1,2,3)

a, a.shape, a.size(), list(a.shape)

(tensor([[[0.0938, 0.0413, 0.3494],
          [0.5211, 0.1257, 0.7845]]]),
 torch.Size([1, 2, 3]),
 torch.Size([1, 2, 3]),
 [1, 2, 3])

In [28]:
# Dim 4

a = torch.rand(2,3,28,28)

a.shape, a.dim()

(torch.Size([2, 3, 28, 28]), 4)

In [26]:
# 占用数据内存

a.numel()

4704