In [1]:
import torch
import numpy as np

In [6]:
# import from numpy array

a = torch.from_numpy(np.array([[1.,2,3], 
                               [4,5,6]]))

print(a, a.shape)


b = torch.from_numpy(np.ones((2,3)))

print(b, b.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64) torch.Size([2, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) torch.Size([2, 3])


In [7]:
# import from a list 

a = torch.tensor([1.,2])
print(a, a.shape)

tensor([1., 2.]) torch.Size([2])


In [9]:
# uninitialized

# empty()

a = torch.empty((2,3))
print(a)

b = torch.Tensor(2,3)
print(b)

tensor([[4.2931e-08, 2.1748e+23, 5.3596e-08],
        [2.1274e+23, 3.3245e+21, 1.3235e-08]])
tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 5.9694e-39]])


In [10]:
# set default type
# torch.set_default_tensor_type()

In [12]:
# 随机初始化 rand/rand_like randint
# rand-[0, 1] 均匀分布

a = torch.rand((3,3), dtype=torch.float32)
print(a)

b = torch.rand_like(a, dtype=torch.float32)
print(b)

c = torch.randint(1,10,(3,3), dtype=torch.float32)
print(c)

tensor([[0.4751, 0.1222, 0.2318],
        [0.5496, 0.5244, 0.5042],
        [0.8128, 0.9891, 0.3477]])
tensor([[0.4426, 0.7971, 0.0644],
        [0.4562, 0.2056, 0.5169],
        [0.4098, 0.5609, 0.6190]])
tensor([[1., 9., 5.],
        [2., 1., 5.],
        [6., 7., 5.]])


In [18]:
# rand- mean0, std 1 正态分布/高斯分布

a = torch.rand(2,3)
print(a)

# b = torch.normal(mean=torch.full([10], 0), std=torch.arange(1, 0, -0.1))

tensor([[0.8702, 0.7870, 0.7774],
        [0.6119, 0.5421, 0.8703]])


In [19]:
# full

a = torch.full((2,3), 6)
print(a)

b = torch.full([], 6)
print(b)

c = torch.full([2], 6)
print(c)

tensor([[6, 6, 6],
        [6, 6, 6]])
tensor(6)
tensor([6, 6])


In [22]:
# arange/range(不建议使用)
a = torch.arange(1,10)
print(a)

b = torch.arange(1,10,2)
print(b)

# linspace/logspace
c = torch.linspace(0,10,steps=3)
print(c)

d = torch.logspace(0,10, steps=3)
print(d)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([1, 3, 5, 7, 9])
tensor([ 0.,  5., 10.])
tensor([1.0000e+00, 1.0000e+05, 1.0000e+10])


In [23]:
# ones/zeros/eye

torch.ones(2,3), torch.zeros(2,3), torch.eye(2,3)

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 0., 0.],
         [0., 1., 0.]]))

In [25]:
# randperm

a = torch.randn(2,3)
b = torch.randn(2,2)

print(a,'\n', b)

tensor([[ 0.4163,  0.0347,  0.7991],
        [-2.8817,  1.1018, -0.0939]]) 
 tensor([[-0.9397,  1.5510],
        [-0.6934,  1.2888]])


In [26]:
idx = torch.randperm(2)
print(idx)

tensor([1, 0])


In [27]:
a[idx], b[idx]

(tensor([[-2.8817,  1.1018, -0.0939],
         [ 0.4163,  0.0347,  0.7991]]),
 tensor([[-0.6934,  1.2888],
         [-0.9397,  1.5510]]))