In [1]:
import torch
import numpy as np

In [3]:
# Indexing
a = torch.rand(2,2,5,5)
print(a)

tensor([[[[0.0844, 0.2688, 0.6317, 0.7093, 0.3250],
          [0.9875, 0.9902, 0.6603, 0.7068, 0.0769],
          [0.6640, 0.7383, 0.1134, 0.1184, 0.5315],
          [0.4727, 0.4396, 0.8889, 0.1888, 0.6718],
          [0.5101, 0.8491, 0.7320, 0.1565, 0.8890]],

         [[0.1700, 0.4932, 0.2697, 0.2675, 0.6286],
          [0.6467, 0.2460, 0.1042, 0.7223, 0.0078],
          [0.2350, 0.1923, 0.4914, 0.4814, 0.1622],
          [0.0540, 0.6460, 0.4444, 0.4351, 0.4301],
          [0.7161, 0.0819, 0.2192, 0.4439, 0.9409]]],


        [[[0.0937, 0.6376, 0.7425, 0.4724, 0.0527],
          [0.8662, 0.1590, 0.7765, 0.8578, 0.8867],
          [0.7595, 0.3165, 0.8964, 0.8338, 0.8390],
          [0.9897, 0.2785, 0.6116, 0.4312, 0.6810],
          [0.9170, 0.2547, 0.1730, 0.7956, 0.3695]],

         [[0.2855, 0.6693, 0.0091, 0.9825, 0.1015],
          [0.0093, 0.6746, 0.7691, 0.6342, 0.8214],
          [0.2159, 0.1439, 0.6445, 0.4142, 0.8654],
          [0.2427, 0.7731, 0.8549, 0.3940, 0.9773],
    

In [4]:
a[0].shape, a[0,0].shape, a[0, 0, 2, 4]

(torch.Size([2, 5, 5]), torch.Size([5, 5]), tensor(0.5315))

In [6]:
# select first/last N

a.shape, a[:1].shape, a[-1:].shape, a[:2, -1:].shape

(torch.Size([2, 2, 5, 5]),
 torch.Size([1, 2, 5, 5]),
 torch.Size([1, 2, 5, 5]),
 torch.Size([2, 1, 5, 5]))

In [7]:
# select by steps

a[:,:,0:5:2,:].shape, a[:,:,::2,::2].shape

(torch.Size([2, 2, 3, 5]), torch.Size([2, 2, 3, 3]))

In [14]:
# select by specific index

a.index_select(0, torch.tensor(1)).shape, a.index_select(3, torch.arange(4)).shape

(torch.Size([1, 2, 5, 5]), torch.Size([2, 2, 5, 4]))

In [15]:
# ...

a.shape, a[1,...].shape

(torch.Size([2, 2, 5, 5]), torch.Size([2, 5, 5]))

In [17]:
# select by mask

mask = a.ge(0.5)
print(mask, mask.shape)  # print all of the number >0.5

tensor([[[[False, False,  True,  True, False],
          [ True,  True,  True,  True, False],
          [ True,  True, False, False,  True],
          [False, False,  True, False,  True],
          [ True,  True,  True, False,  True]],

         [[False, False, False, False,  True],
          [ True, False, False,  True, False],
          [False, False, False, False, False],
          [False,  True, False, False, False],
          [ True, False, False, False,  True]]],


        [[[False,  True,  True, False, False],
          [ True, False,  True,  True,  True],
          [ True, False,  True,  True,  True],
          [ True, False,  True, False,  True],
          [ True, False, False,  True, False]],

         [[False,  True, False,  True, False],
          [False,  True,  True,  True,  True],
          [False, False,  True, False,  True],
          [False,  True,  True, False,  True],
          [ True, False,  True,  True, False]]]]) torch.Size([2, 2, 5, 5])


In [19]:
torch.masked_select(a, mask), torch.masked_select(a,mask).shape

(tensor([0.6317, 0.7093, 0.9875, 0.9902, 0.6603, 0.7068, 0.6640, 0.7383, 0.5315,
         0.8889, 0.6718, 0.5101, 0.8491, 0.7320, 0.8890, 0.6286, 0.6467, 0.7223,
         0.6460, 0.7161, 0.9409, 0.6376, 0.7425, 0.8662, 0.7765, 0.8578, 0.8867,
         0.7595, 0.8964, 0.8338, 0.8390, 0.9897, 0.6116, 0.6810, 0.9170, 0.7956,
         0.6693, 0.9825, 0.6746, 0.7691, 0.6342, 0.8214, 0.6445, 0.8654, 0.7731,
         0.8549, 0.9773, 0.7277, 0.6788, 0.6757]),
 torch.Size([50]))

In [21]:
# select by flatten index

torch.take(a, torch.tensor([9,8,5])), torch.take(a, torch.tensor([9,8,5])).shape

(tensor([0.0769, 0.7068, 0.9875]), torch.Size([3]))