In [1]:
import torch
import numpy as np

In [3]:
# case
a = torch.randn(2,3)
print(a)

b = torch.rand(1)
print(b)

tensor([[-1.6907, -0.7281, -0.4768],
        [ 1.5135,  0.5332, -0.5031]])
tensor([0.5002])


In [4]:
a+b  # is juet like broadcast

tensor([[-1.1906, -0.2280,  0.0234],
        [ 2.0136,  1.0334, -0.0030]])

In [7]:
# situation 1

a = torch.Tensor(4,32,14,14)
print(a.shape)

b = torch.Tensor(1,32,1,1)
print(b.shape)

print((a+b).shape)

torch.Size([4, 32, 14, 14])
torch.Size([1, 32, 1, 1])
torch.Size([4, 32, 14, 14])


In [8]:
# situation 2

print(a.shape)

c = torch.Tensor(14,14)
print(c.shape)

print((a+c).shape)

torch.Size([4, 32, 14, 14])
torch.Size([14, 14])
torch.Size([4, 32, 14, 14])


In [9]:
# situation 3

# match from the last dim
#  if a-[4,32,14,14]
#     d-[2,32,14,14]
#  then they can not plus

print(a.shape)

d = torch.Tensor(2,32,14,14)

a+d

torch.Size([4, 32, 14, 14])


RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 0