In [2]:
import torch
import numpy as np

In [3]:
# + - * /
a = torch.rand(2,3)
b = torch.rand(2,3)

print(torch.all(torch.eq(a+b, torch.add(a,b))))
print(torch.all(torch.eq(a-b, torch.sub(a,b))))
print(torch.all(torch.eq(a*b, torch.mul(a,b))))
print(torch.all(torch.eq(a/b, torch.div(a,b))))

tensor(True)
tensor(True)
tensor(True)
tensor(True)


In [7]:
# matmul  矩阵相乘
# torch.mm - only for 2D
# torch.matmul
# @

print(torch.all(torch.eq(a@b.T, torch.mm(a,b.T))))
print(torch.all(torch.eq(a@b.T, torch.matmul(a,b.T))))

tensor(True)
tensor(True)


In [9]:
# >2D tensor matmul

a = torch.Tensor(4,3,32,64)
b = torch.Tensor(4,1,64,32)

(a@b).shape

torch.Size([4, 3, 32, 32])

In [13]:
# power 次方
x = torch.full([2,2], 3)

print(torch.all(torch.eq(x**2, torch.pow(x,2))))
print(torch.all(torch.eq(x**3, x.pow(3))))

tensor(True)
tensor(True)


In [15]:
# exp log(默认以e为底)

a = torch.exp(torch.ones(2,2))
print(a)

print(torch.log(a))

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])
tensor([[1., 1.],
        [1., 1.]])


In [18]:
# Approximation
# .floor() .ceil() .round() .trunc() .frac()

a = torch.tensor(3.14)

a.floor(), a.ceil(), a.round(), a.trunc(), a.frac()

(tensor(3.), tensor(4.), tensor(3.), tensor(3.), tensor(0.1400))

In [24]:
# clamp 
# gradient clipping

grad = torch.rand(2,3)*15
print(grad)

print(grad.clamp(10), '\n', torch.clamp(grad, 0, 10))

tensor([[ 8.9766, 14.3457, 10.7882],
        [ 7.6952, 10.0894,  8.0403]])
tensor([[10.0000, 14.3457, 10.7882],
        [10.0000, 10.0894, 10.0000]]) 
 tensor([[ 8.9766, 10.0000, 10.0000],
        [ 7.6952, 10.0000,  8.0403]])


In [38]:
# statistics
# norm mean/sum prod  max/min/argmin/argmax kthvalue/topk

# norm
# is not normalize
# matrix norm v.s. vector norm

a = torch.full([2,3], 1, dtype=torch.float32)
print(a,a.shape)

print(a.norm(1), a.norm(1, dim=0), torch.norm(a, 2, dim=0))

tensor([[1., 1., 1.],
        [1., 1., 1.]]) torch.Size([2, 3])
tensor(6.) tensor([2., 2., 2.]) tensor([1.4142, 1.4142, 1.4142])


In [45]:
# mean/sum prod  max/min/argmin/argmax

a = torch.arange(10).reshape(2,5).float()
print(a)

print(a.mean(), a.sum(), a.prod(), a.max(), a.min(), a.argmax(), a.argmin())

print('dim 1: ', a.mean(0), a.sum(0), a.prod(0), a.max(0), a.min(0))
print('dim 2: ', a.mean(1), a.sum(1), a.prod(1), a.max(1), a.min(1))

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])
tensor(4.5000) tensor(45.) tensor(0.) tensor(9.) tensor(0.) tensor(9) tensor(0)
dim 1:  tensor([2.5000, 3.5000, 4.5000, 5.5000, 6.5000]) tensor([ 5.,  7.,  9., 11., 13.]) tensor([ 0.,  6., 14., 24., 36.]) torch.return_types.max(
values=tensor([5., 6., 7., 8., 9.]),
indices=tensor([1, 1, 1, 1, 1])) torch.return_types.min(
values=tensor([0., 1., 2., 3., 4.]),
indices=tensor([0, 0, 0, 0, 0]))
dim 2:  tensor([2., 7.]) tensor([10., 35.]) tensor([    0., 15120.]) torch.return_types.max(
values=tensor([4., 9.]),
indices=tensor([4, 4])) torch.return_types.min(
values=tensor([0., 5.]),
indices=tensor([0, 0]))


In [49]:
a.argmax(0), a.argmin(0)  # 返回的是索引号

(tensor([1, 1, 1, 1, 1]), tensor([0, 0, 0, 0, 0]))

In [51]:
# dim keepdim

a.argmax(1, keepdim=True), a.argmax(1).shape, a.argmax(1, keepdim=True).shape

(tensor([[4],
         [4]]),
 torch.Size([2]),
 torch.Size([2, 1]))

In [5]:
# top-k and k-th

b = torch.rand(2,3)

print(b.topk(3, dim=1))
print(b.topk(3, dim=1, largest=False))

print(b.kthvalue(2, dim=1))

torch.return_types.topk(
values=tensor([[0.2897, 0.1929, 0.0727],
        [0.8875, 0.4714, 0.3232]]),
indices=tensor([[0, 2, 1],
        [2, 0, 1]]))
torch.return_types.topk(
values=tensor([[0.0727, 0.1929, 0.2897],
        [0.3232, 0.4714, 0.8875]]),
indices=tensor([[1, 2, 0],
        [1, 0, 2]]))
torch.return_types.kthvalue(
values=tensor([0.1929, 0.4714]),
indices=tensor([2, 0]))


In [6]:
# compare 
# > < ==  !=
# torch.eq()/torch.equal()

In [8]:
# where gather

# where torch.where(condition, x, y)
a = torch.ones(2,3)
b = torch.zeros(2,3)

cond = torch.tensor([[0.2, 0.6, 0.1], [0.8, 0.3, 0.7]])

torch.where(cond>0.5, a, b)

tensor([[0., 1., 0.],
        [1., 0., 1.]])

In [9]:
# gather torch.gather(input, dim, index, out=None) ->Tensor

# out[i][j][k] = input[index[i][j][k]][j][k]  # if dim == 0
# out[i][j][k] = input[i][index[i][j][k]][k]  # if dim == 1
# out[i][j][k] = input[i][j][index[i][j][k]]  # if dim == 2
# https://pytorch.org/docs/stable/generated/torch.gather.html?highlight=torch%20gather#torch.gather

t = torch.tensor([[1, 2], [3, 4]])
torch.gather(t, 1, torch.tensor([[0, 0], [1, 0]]))

tensor([[1, 1],
        [4, 3]])